### ISSUE TITLE
Helm Hub

### ISSUE THREAD

**Issue by austince** [newrelic/kubernetes-logging#24]
Hi there,

Has newrelic thought about integrating your Helm charts with the new [`hub.helm.sh`](https://github.com/helm/hub/blob/master/README.md) platform? Would make it much easier to work with your charts.

Thanks! 
Austin

**Comment by alejandrodnm** [comment]
Hi @austince, thanks for the suggestion, we already have this in our roadmap, but I don't know when the work on it will start.

**Comment by nagonzalez** [comment]
In the interim, anyway you folks could package the chart `.tgz` and include it as part of a GitHub release? We use terraform to install other charts and would love to do something like:

```
resource "helm_release" "kubernetes_logging" {
  chart     = "https://github.com/newrelic/kubernetes-logging/releases/download/1.0.2/helm-chart.tgz"
  name      = "newrelic-logging"
  namespace = "newrelic-logging"
}
```

**Comment by alejandrodnm** [comment]
@nagonzalez we will start working on this next week or the other, so we should have our own helm repo indexed in helm hub fairly soon.

I'll update this ticket once it's done.

**Comment by jdn-za** [comment]
Looking forward to this too!

**Comment by alejandrodnm** [comment]
We are still in the process of being added to helm hub (we already applied), but we already have the helm repo ready, you can check it out (and start contributing :D ) here

https://github.com/newrelic/helm-charts

**Comment by nagonzalez** [comment]
this is awesome! thanks!

**Comment by austince** [comment]
Looks like it's been listed! https://github.com/helm/hub/pull/364
