### ISSUE TITLE
Add the ability to add additional attributes to the Logger

### ISSUE THREAD

**Issue by WilliamABradley** [newrelic/kubernetes-logging#31]
It would be great if we could easily add global attributes to the Logger.

E.g.
Cluster: {Kubernetes Cluster Name}
Region: {Kubernetes Cluster hosted region}
and more...

If we could achieve that by customising the Helm Chart, or by adding Environment Variables, that would be great.

**Comment by jsubirat** [comment]
This issue has been moved here: https://github.com/newrelic/helm-charts/issues/75
