### ISSUE TITLE
new FILTER "grep" rule doesn't work

### ISSUE THREAD

**Issue by d00m178** [newrelic/kubernetes-logging#34]
I have changed the filter-kubenetes.con part in fluent-conf.yml:

```
  filter-kubernetes.conf: |
    [FILTER]
        Name record_modifier
        Match *
        Record cluster_name ${CLUSTER_NAME}

    [FILTER]
        Name           kubernetes
        Match          kube.*
        Kube_URL       https://kubernetes.default.svc.cluster.local:443
        Merge_JSON_Log Off

    [FILTER]
        Name grep
        Match *
        Exclude message HealthChecker
```

And want to exclude log messages like:
172.18.110.109 - - [29/May/2020:13:02:35 +0000] "GET / HTTP/1.1" 200 2804 "-" "ELB-HealthChecker/2.0" "-"

But seem it doesn't work - such log messages still coming to NR Logs page.
Also I checked:          

`Exclude log HealthChecker
`
the same behavior.
Please advice - is the Filter rules works in New Relic Fluent Bit output plugin for Kubernetes?

**Comment by jsubirat** [comment]
Hi @d00m178 , this repository has been deprecated and moved [here](https://github.com/newrelic/helm-charts). I have moved your issue [here](https://github.com/newrelic/helm-charts/issues/77).
