### ISSUE TITLE
This chart's DaemonSet apiVersion is deprecated and removed

### ISSUE THREAD

**Issue by 01100010011001010110010101110000** [newrelic/kubernetes-logging#35]
The DaemonSet resource is no longer served from `apps/v1beta2` as of [Kubernetes `1.16`](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/). 

You can use `Capabilities.KubeVersion` in your helm chart to check if the target cluster is `1.9` or higher and use the `apps/v1` if so.

**Comment by jsubirat** [comment]
Hi 01100010011001010110010101110000 (p),

This repository has been moved to [New Relic's helm charts repository](https://github.com/newrelic/helm-charts/) (the chart is now named _newrelic-logging_). I observed that during the process, the _apiVersion_ has been homogenized, see [here](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/templates/daemonset.yaml#L2). I am closing this ticket, but feel free to open a new one in the new repository if this solution doesn't work for you. Thanks a lot!
