### ISSUE TITLE
Feature Request - Add ability to tag the resources you want the logs captures (or opt-out)

### ISSUE THREAD

**Issue by shicholas** [newrelic/kubernetes-logging#36]
Installation and setup with this was easy and straightforward, nice work!

It'd be nice to opt-in or out of New Relic collecting logs based on metadata tags we assign to our K8 resources, or specify a K8 namespace to collect logs from. We have some third-party managed resources we do not care to collect logs from (e.g. Azure's Key Vault).

**Comment by jsubirat** [comment]
Hi @shicholas , this repository has been deprecated and moved [here](https://github.com/newrelic/helm-charts). I moved your issue [here](https://github.com/newrelic/helm-charts/issues/78).
