### ISSUE TITLE
Feature Request - Custom Fluentd config

### ISSUE THREAD

**Issue by ghost** [newrelic/kubernetes-logging#37]
We'd like to have two Fluentd outs, one to New Relic, and the other to our archival storage. If custom `fluentd.conf` are possible today, the documentation isn't clear on how to do so. If not, then I'm happy to write a PR if you point me in the write direction.

**Comment by jsubirat** [comment]
Hi @shicholas , we are deprecating this repository, as it has been moved [here](https://github.com/newrelic/helm-charts). I have created a new issue with your request [here](https://github.com/newrelic/helm-charts/issues/76). Closing this ticket.
